package com.example.banking.model;

public enum OperationType {
    LOGIN_FAILURE,
    LOGIN_SUCCESS,
    OTP_VERIFIED,
    TRANSFER_CREATED,
    PAYMENT_CREATED,
    STATEMENT_DOWNLOADED,
    HISTORY_DOWNLOADED,
    ACCOUNT_BLOCK_REQUESTED,
    ACCOUNT_BLOCKED,
    ACCOUNT_UNBLOCKED,
    ACCESS_UNBLOCKED,
    CUSTOMER_REGISTERED
}
